theme: jekyll-theme-architect
title: Buomsoo Kim
description: "Welcome to my homepage! You are welcome to use & contribute to projects that are shared via my page"
url: "http://buomsoo-kim.github.io"
author:
  name: "Buomsoo Kim"
  email: "buomsookim@email.arizona.edu"
  url: "http://buomsoo-kim.github.io"
